package com.nova.backend.message;
import com.nova.backend.mobile.MobileSessionAuthenticator; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/mobile/messages") public class MobileMessageController { private static final UUID ORG=UUID.fromString("00000000-0000-0000-0000-000000000001"); private final MessageRepository repo; private final MobileSessionAuthenticator auth; private final TypingRegistry typing; public MobileMessageController(MessageRepository repo,MobileSessionAuthenticator auth,TypingRegistry typing){this.repo=repo;this.auth=auth;this.typing=typing;}
 @GetMapping public List<MessageThread> list(@RequestHeader(value="Authorization",required=false)String authorization){return repo.contractorThreads(auth.authenticate(authorization).contractorId());}
 @PostMapping("/requests") @org.springframework.web.bind.annotation.ResponseStatus(org.springframework.http.HttpStatus.CREATED) public MessageThread request(@RequestHeader(value="Authorization",required=false)String authorization,@Valid @RequestBody Send body){return repo.request(ORG,auth.authenticate(authorization).contractorId(),body.body());}
 @PostMapping("/{id}/read") public MessageThread read(@RequestHeader(value="Authorization",required=false)String authorization,@PathVariable UUID id){return repo.readByTalent(id,auth.authenticate(authorization).contractorId());}
 @PostMapping("/{id}/messages") public ThreadMessage send(@RequestHeader(value="Authorization",required=false)String authorization,@PathVariable UUID id,@Valid @RequestBody Send body){ThreadMessage sent=repo.sendTalent(id,auth.authenticate(authorization).contractorId(),body.body());typing.clear(id,"TALENT");return sent;}
 /** The candidate is typing in this thread; expires after a few seconds without another call. */
 @PostMapping("/{id}/typing") @org.springframework.web.bind.annotation.ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) public void typing(@RequestHeader(value="Authorization",required=false)String authorization,@PathVariable UUID id){repo.requireTalentThread(id,auth.authenticate(authorization).contractorId());typing.mark(id,"TALENT");}
 /** Whether the business is currently typing in this thread. */
 @GetMapping("/{id}/typing") public BusinessMessageController.Typing typingState(@RequestHeader(value="Authorization",required=false)String authorization,@PathVariable UUID id){repo.requireTalentThread(id,auth.authenticate(authorization).contractorId());return new BusinessMessageController.Typing(typing.isTyping(id,"BUSINESS"));}
 public record Send(@NotBlank @Size(max=4000)String body){}
}
