import type { CandidateApplication } from "@/types/application";

export const demoApplications: CandidateApplication[] = [
  {
    id: "application-tran-bao",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    applicantUserId: "user-tran-bao",
    candidateName: "Trần Quốc Bảo",
    initials: "TB",
    username: "@tranbao.dev",
    statusBadge: "Đang xem",
    headline: "Frontend Developer",
    email: "bao.tran@example.com",
    location: "Đà Nẵng, Việt Nam",
    timezone: "UTC+7",
    languages: "Tiếng Việt · English",
    workType: "Toàn thời gian · Remote",
    capacity: "40 giờ/tuần",
    profileCompletion: 92,
    completionTip: "Hồ sơ đã đầy đủ chứng chỉ chuyên môn Flutter và Solana.",
    trustRank: "Bậc Đồng",
    trustRankSubtitle: "Cấp bậc uy tín Nova",
    bio: "Chuyên gia phát triển ứng dụng di động Flutter và giao diện web với 3 năm kinh nghiệm trong lĩnh vực fintech và cổng thanh toán blockchain.",
    matchScore: 94,
    skills: ["Flutter", "Dart", "Firebase", "TypeScript", "Solana Pay", "Git"],
    detailedSkills: ["Flutter", "Dart", "Firebase", "TypeScript", "Solana Pay", "Git"],
    coverNote:
      "Mình đã xây dựng hai ứng dụng Flutter có luồng thanh toán và muốn trao đổi thêm về phạm vi tích hợp của dự án.",
    portfolioLabel: "github.com/tranbao",
    portfolioPreview: [
      {
        id: "tb-1",
        title: "Ví điện tử Nova Mobile",
        thumbnailUrl: "/images/payment-network.webp",
        url: "https://github.com/tranbao/nova-mobile",
        description: "Ứng dụng ví thanh toán di động hỗ trợ Solana Pay",
      },
      {
        id: "tb-2",
        title: "Cổng thanh toán Solana Pay",
        url: "https://github.com/tranbao/solana-pay-gateway",
        description: "Module tích hợp chuẩn thanh toán trực tiếp qua QR code",
      },
    ],
    detailedPortfolio: [
      {
        id: "tb-1",
        title: "Ví điện tử Nova Mobile",
        role: "Lead Mobile Developer",
        description: "Ứng dụng ví thanh toán di động hỗ trợ Solana Pay và giao dịch siêu tốc.",
        badge: "Đang phát triển",
        badgeTone: "amber",
        url: "https://github.com/tranbao/nova-mobile",
        techTags: ["Flutter", "Dart", "Solana Pay"],
      },
      {
        id: "tb-2",
        title: "Cổng thanh toán Solana Pay",
        role: "Software Architect",
        description: "Module tích hợp chuẩn thanh toán trực tiếp qua mã QR cho các chuỗi bán lẻ.",
        badge: "Hoàn tất",
        badgeTone: "green",
        url: "https://github.com/tranbao/solana-pay-gateway",
        techTags: ["TypeScript", "Solana", "Web3"],
      },
    ],
    experiences: [
      {
        id: "exp-tb-1",
        role: "Senior Frontend Engineer",
        company: "Fintech Solutions Vietnam",
        period: "2023 - nay",
        description: "Phát triển ứng dụng mobile banking và tích hợp luồng QR thanh toán quốc tế.",
      },
    ],
    education: {
      degree: "Kỹ sư Công nghệ Thông tin",
      institution: "Đại học Bách Khoa Đà Nẵng",
      years: "2019 - 2023",
      note: "Tốt nghiệp loại Giỏi",
    },
    privacyNotice: "Email, số điện thoại, tài khoản ngân hàng và địa chỉ ví không xuất hiện trong hồ sơ này.",
    availability: "Có thể bắt đầu trong 1 tuần",
    status: "viewed",
    submittedAt: "11/09/2026 · 15:20",
    createdAt: "2026-09-11T15:20:00Z",
    updatedAt: "2026-09-11T16:05:00Z",
    messages: [
      {
        id: "message-bao-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được gửi đến Nova Labs.",
        sentAt: "15:20",
      },
      {
        id: "message-bao-business",
        role: "BUSINESS",
        senderName: "Nova Labs",
        body: "Chào Bảo, đội ngũ đã nhận hồ sơ và đang xem phần kinh nghiệm Flutter của bạn.",
        sentAt: "16:05",
        deliveryStatus: "SEEN",
      },
      {
        id: "message-bao-talent",
        role: "TALENT",
        senderName: "Trần Quốc Bảo",
        body: "Cảm ơn đội ngũ. Mình có thể gửi thêm bản demo luồng thanh toán nếu cần.",
        sentAt: "16:12",
        deliveryStatus: "SEEN",
        replyToId: "message-bao-business",
      },
    ],
  },
  {
    id: "application-minh-anh",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    applicantUserId: "user-minh-anh",
    candidateName: "Minh Anh",
    initials: "MA",
    username: "@minhanh.nova",
    avatarUrl: "/images/avatar-minh-anh.png",
    statusBadge: "Sẵn sàng",
    headline: "Flutter Developer | Fintech Mobile Applications",
    email: "minh.anh@example.com",
    location: "Đà Nẵng, Việt Nam",
    timezone: "UTC+7",
    languages: "Tiếng Việt · English",
    workType: "Remote · Theo dự án",
    capacity: "20 giờ/tuần",
    profileCompletion: 86,
    completionTip: "Bổ sung chứng chỉ để doanh nghiệp có thêm cơ sở đánh giá.",
    trustRank: "Chưa xếp hạng",
    trustRankSubtitle: "Cấp bậc uy tín Nova",
    bio: "Tôi xây dựng ứng dụng Flutter cho fintech và các sản phẩm thanh toán. Tôi tập trung vào giao diện responsive, code dễ bảo trì và tiến độ minh bạch theo từng giai đoạn.",
    matchScore: 96,
    skills: ["Flutter", "Dart", "Java", "Spring Boot", "PostgreSQL", "REST API", "Solana", "Git"],
    detailedSkills: ["Flutter", "Dart", "Java", "Spring Boot", "PostgreSQL", "REST API", "Solana", "Git"],
    coverNote:
      "Mình quan tâm đến cách Nova kết nối trải nghiệm nhận việc với luồng chi trả USDC trên mobile.",
    portfolioLabel: "github.com/minhanh-dev",
    portfolioPreview: [
      {
        id: "ma-1",
        title: "Nova Mobile Prototype",
        thumbnailUrl: "/images/dashboard-preview.webp",
        url: "https://github.com/minhanh-dev/nova-mobile-prototype",
        description: "Ứng dụng hỗ trợ freelancer tìm việc, trao đổi và theo dõi thanh toán quốc tế.",
      },
      {
        id: "ma-2",
        title: "Nova Business",
        url: "https://github.com/minhanh-dev/nova-business",
        description: "Không gian doanh nghiệp để đăng cơ hội, xét duyệt ứng viên và quản lý yêu cầu thanh toán.",
      },
    ],
    detailedPortfolio: [
      {
        id: "portfolio-nova-mobile",
        title: "Nova Mobile Prototype",
        role: "Flutter Developer",
        description: "Ứng dụng hỗ trợ freelancer tìm việc, trao đổi và theo dõi thanh toán quốc tế.",
        badge: "Prototype",
        badgeTone: "amber",
        url: "https://github.com/minhanh-dev/nova-mobile-prototype",
        techTags: ["Flutter", "Dart", "Solana Devnet"],
      },
      {
        id: "portfolio-nova-business",
        title: "Nova Business",
        role: "Product & Frontend Developer",
        description: "Không gian doanh nghiệp để đăng cơ hội, xét duyệt ứng viên và quản lý yêu cầu thanh toán.",
        badge: "Đang phát triển",
        badgeTone: "amber",
        url: "https://github.com/minhanh-dev/nova-business",
        techTags: ["Next.js", "TypeScript", "UI/UX"],
      },
    ],
    experiences: [
      {
        id: "exp-1",
        role: "Flutter Developer",
        company: "Independent Freelancer",
        period: "2024 - nay",
        description: "Xây dựng auth flow, wallet, payment request và kiểm thử responsive trên thiết bị Android thật.",
      },
    ],
    education: {
      degree: "Kỹ thuật phần mềm",
      institution: "Đại học FPT Đà Nẵng · Sinh viên",
      years: "2023 - 2027",
      note: "Thông tin do người dùng tự khai",
    },
    privacyNotice: "Email, số điện thoại, tài khoản ngân hàng và địa chỉ ví không xuất hiện trong hồ sơ này.",
    availability: "Sẵn sàng từ 18/09/2026",
    status: "submitted",
    submittedAt: "12/09/2026 · 09:42",
    createdAt: "2026-09-12T09:42:00Z",
    updatedAt: "2026-09-12T09:42:00Z",
    messages: [
      {
        id: "message-anh-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được gửi đến Nova Labs.",
        sentAt: "09:42",
      },
      {
        id: "message-anh-talent",
        role: "TALENT",
        senderName: "Minh Anh",
        body: "Chào đội ngũ, mình sẵn sàng trao đổi thêm về kinh nghiệm Flutter và tích hợp API.",
        sentAt: "09:44",
        deliveryStatus: "DELIVERED",
      },
    ],
  },
  {
    id: "application-linh-nguyen",
    jobId: "job-product-designer",
    jobTitle: "Product Designer - Remote Workflows",
    applicantUserId: "user-linh-nguyen",
    candidateName: "Nguyễn Khánh Linh",
    initials: "KL",
    username: "@khanhlinh.design",
    statusBadge: "Đã chọn",
    headline: "Product Designer",
    email: "linh.nguyen@example.com",
    location: "Hà Nội, Việt Nam",
    timezone: "UTC+7",
    languages: "Tiếng Việt · English",
    workType: "Remote · Theo dự án",
    capacity: "25 giờ/tuần",
    profileCompletion: 89,
    completionTip: "Bổ sung thêm video demo prototype Figma tương tác.",
    trustRank: "Bậc Bạc",
    trustRankSubtitle: "Cấp bậc uy tín Nova",
    bio: "Senior Product Designer chuyên sâu về design system, UX flows cho ứng dụng ví tiền mã hóa và dashboard quản lý tài chính doanh nghiệp.",
    matchScore: 88,
    skills: ["Figma", "UX Research", "Design System", "Prototyping", "UI Design"],
    detailedSkills: ["Figma", "UX Research", "Design System", "Prototyping", "UI Design"],
    coverNote:
      "Mình có kinh nghiệm thiết kế sản phẩm fintech và quy trình cộng tác cho đội ngũ phân tán.",
    portfolioLabel: "khanhlinh.design",
    portfolioPreview: [
      {
        id: "kl-1",
        title: "Fintech Dashboard Redesign",
        url: "https://khanhlinh.design/fintech-dashboard",
        description: "Giao diện quản lý dòng tiền và thanh toán xuyên biên giới",
      },
      {
        id: "kl-2",
        title: "Web3 Wallet Onboarding",
        url: "https://khanhlinh.design/web3-wallet",
        description: "Quy trình tạo ví và bảo mật tài sản số không mật khẩu",
      },
    ],
    detailedPortfolio: [
      {
        id: "kl-1",
        title: "Fintech Dashboard Redesign",
        role: "Lead UI/UX Designer",
        description: "Giao diện quản lý dòng tiền và thanh toán xuyên biên giới cho doanh nghiệp vừa và nhỏ.",
        badge: "Hoàn tất",
        badgeTone: "green",
        url: "https://khanhlinh.design/fintech-dashboard",
        techTags: ["Figma", "Design System", "Fintech"],
      },
      {
        id: "kl-2",
        title: "Web3 Wallet Onboarding",
        role: "UX Researcher",
        description: "Quy trình tạo ví và bảo mật tài sản số không mật khẩu với tỷ lệ hoàn tất 95%.",
        badge: "Hoàn tất",
        badgeTone: "green",
        url: "https://khanhlinh.design/web3-wallet",
        techTags: ["UX Research", "Web3", "Figma"],
      },
    ],
    experiences: [
      {
        id: "exp-kl-1",
        role: "Senior Product Designer",
        company: "Creative Studio Hanoi",
        period: "2022 - nay",
        description: "Chủ trì xây dựng hệ thống design system cho 5 ứng dụng fintech quốc tế.",
      },
    ],
    education: {
      degree: "Cử nhân Thiết kế Đồ họa",
      institution: "Đại học Mỹ thuật Công nghiệp Hà Nội",
      years: "2018 - 2022",
      note: "Thủ khoa chuyên ngành",
    },
    privacyNotice: "Email, số điện thoại, tài khoản ngân hàng và địa chỉ ví không xuất hiện trong hồ sơ này.",
    availability: "Có thể bắt đầu ngay",
    status: "shortlisted",
    submittedAt: "10/09/2026 · 11:08",
    createdAt: "2026-09-10T11:08:00Z",
    updatedAt: "2026-09-10T14:30:00Z",
    messages: [
      {
        id: "message-linh-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được duyệt vào Shortlist. Hai bên có thể tiếp tục trao đổi.",
        sentAt: "14:30",
      },
    ],
  },
  {
    id: "application-phuong-thao",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    applicantUserId: "user-phuong-thao",
    candidateName: "Vũ Phương Thảo",
    initials: "PT",
    username: "@phuongthao.rust",
    statusBadge: "Phỏng vấn",
    headline: "Senior Mobile Engineer",
    email: "thao.vu@example.com",
    location: "Hà Nội, Việt Nam",
    timezone: "UTC+7",
    languages: "Tiếng Việt · English",
    workType: "Toàn thời gian · Remote",
    capacity: "40 giờ/tuần",
    profileCompletion: 95,
    completionTip: "Hồ sơ đã đạt mức tín nhiệm tối đa trong danh mục Mobile & Rust.",
    trustRank: "Bậc Vàng",
    trustRankSubtitle: "Cấp bậc uy tín Nova",
    bio: "Senior Mobile Engineer với 4 năm kinh nghiệm chuyên sâu về kiến trúc ứng dụng Flutter quy mô lớn, tích hợp thư viện native Rust và các giải pháp thanh toán phân tán Web3.",
    matchScore: 96,
    skills: ["Flutter", "Dart", "Rust", "Web3", "Solana", "CI/CD"],
    detailedSkills: ["Flutter", "Dart", "Rust", "Web3", "Solana", "CI/CD"],
    coverNote:
      "Mình có 4 năm kinh nghiệm xây dựng ứng dụng fintech và tích hợp ví crypto trên mobile.",
    portfolioLabel: "github.com/phuongthao-dev",
    portfolioPreview: [
      {
        id: "pt-1",
        title: "Crypto Checkout SDK",
        thumbnailUrl: "/images/payment-network.webp",
        url: "https://github.com/phuongthao-dev/crypto-checkout",
        description: "Bộ thư viện Flutter nhúng trực tiếp cổng thanh toán crypto",
      },
    ],
    detailedPortfolio: [
      {
        id: "pt-1",
        title: "Crypto Checkout SDK",
        role: "Core Author & Maintainer",
        description: "Bộ SDK Flutter mã nguồn mở nhúng trực tiếp cổng thanh toán crypto và QR Solana.",
        badge: "Đã phát hành",
        badgeTone: "green",
        url: "https://github.com/phuongthao-dev/crypto-checkout",
        techTags: ["Flutter", "Rust", "Solana"],
      },
    ],
    experiences: [
      {
        id: "exp-pt-1",
        role: "Lead Mobile Developer",
        company: "Global Web3 Foundation",
        period: "2021 - nay",
        description: "Thiết kế kiến trúc ứng dụng ví di động phi tập trung phục vụ hơn 200,000 người dùng tích cực hàng tháng.",
      },
    ],
    education: {
      degree: "Thạc sĩ Khoa học Máy tính",
      institution: "Đại học Quốc gia Hà Nội",
      years: "2017 - 2021",
      note: "Chuyên ngành Mạng máy tính & An toàn thông tin",
    },
    privacyNotice: "Email, số điện thoại, tài khoản ngân hàng và địa chỉ ví không xuất hiện trong hồ sơ này.",
    availability: "Sẵn sàng ngay",
    status: "interview",
    submittedAt: "13/09/2026 · 10:15",
    createdAt: "2026-09-13T10:15:00Z",
    updatedAt: "2026-09-14T14:00:00Z",
    messages: [
      {
        id: "message-thao-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được chọn vào vòng phỏng vấn.",
        sentAt: "10:15",
      },
    ],
  },
  {
    id: "application-quoc-tuan",
    jobId: "job-product-designer",
    jobTitle: "Product Designer - Remote Workflows",
    applicantUserId: "user-quoc-tuan",
    candidateName: "Đặng Quốc Tuấn",
    initials: "QT",
    headline: "Lead UX/UI Designer",
    email: "tuan.dang@example.com",
    location: "Đà Nẵng, Việt Nam",
    matchScore: 92,
    skills: ["Figma", "Design System", "Prototyping"],
    coverNote:
      "Rất hào hứng với cơ hội hợp tác và đã hoàn tất các thỏa thuận công việc cùng Nova Labs.",
    portfolioLabel: "dribbble.com/quoctuan",
    portfolioPreview: [
      {
        id: "qt-1",
        title: "Nova Design Tokens",
        url: "https://dribbble.com/quoctuan/nova-tokens",
        description: "Thư viện design token đa nền tảng trên Figma",
      },
    ],
    availability: "Đang làm việc",
    status: "accepted",
    submittedAt: "08/09/2026 · 08:30",
    createdAt: "2026-09-08T08:30:00Z",
    updatedAt: "2026-09-15T09:00:00Z",
    messages: [
      {
        id: "message-tuan-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được nhận chính thức (Hired).",
        sentAt: "09:00",
      },
    ],
  },
  {
    id: "application-van-hung",
    jobId: "job-rust-solana",
    jobTitle: "Solana Smart Contract Engineer",
    applicantUserId: "user-van-hung",
    candidateName: "Bùi Văn Hùng",
    initials: "VH",
    headline: "Solana / Rust Developer",
    email: "hung.bui@example.com",
    location: "Hà Nội, Việt Nam",
    matchScore: 85,
    skills: ["Rust", "Solana", "Anchor"],
    coverNote:
      "Do đã nhận một dự án dài hạn khác, mình xin phép rút hồ sơ ứng tuyển đợt này. Cảm ơn Nova Labs.",
    portfolioLabel: "github.com/hungbui-sol",
    portfolioPreview: [
      {
        id: "vh-1",
        title: "Solana Escrow Program",
        url: "https://github.com/hungbui-sol/escrow-program",
        description: "Hợp đồng thông minh lưu ký tài sản an toàn trên Solana",
      },
    ],
    availability: "Đã nhận dự án khác",
    status: "withdrawn",
    submittedAt: "09/09/2026 · 14:00",
    createdAt: "2026-09-09T14:00:00Z",
    updatedAt: "2026-09-14T11:20:00Z",
    messages: [
      {
        id: "message-hung-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Ứng viên đã chủ động rút hồ sơ.",
        sentAt: "11:20",
      },
    ],
  },
];
