import type { CandidateApplication } from "@/types/application";

export const demoApplications: CandidateApplication[] = [
  {
    id: "application-tran-bao",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    applicantUserId: "user-tran-bao",
    candidateName: "Trần Quốc Bảo",
    initials: "TB",
    headline: "Frontend Developer",
    email: "bao.tran@example.com",
    location: "Đà Nẵng, Việt Nam",
    matchScore: 94,
    skills: ["Flutter", "Dart", "Firebase"],
    coverNote:
      "Mình đã xây dựng hai ứng dụng Flutter có luồng thanh toán và muốn trao đổi thêm về phạm vi tích hợp của dự án.",
    portfolioLabel: "github.com/tranbao",
    portfolioPreview: [
      {
        id: "tb-1",
        title: "Ví điện tử Nova Mobile",
        thumbnailUrl: "/images/payment-network.webp",
        url: "https://github.com/tranbao/nova-mobile",
        description: "Ứng dụng ví thanh toán di động hỗ trợ Solana Pay",
      },
      {
        id: "tb-2",
        title: "Cổng thanh toán Solana Pay",
        url: "https://github.com/tranbao/solana-pay-gateway",
        description: "Module tích hợp chuẩn thanh toán trực tiếp qua QR code",
      },
    ],
    availability: "Có thể bắt đầu trong 1 tuần",
    status: "viewed",
    submittedAt: "11/09/2026 · 15:20",
    createdAt: "2026-09-11T15:20:00Z",
    updatedAt: "2026-09-11T16:05:00Z",
    messages: [
      {
        id: "message-bao-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được gửi đến Nova Labs.",
        sentAt: "15:20",
      },
      {
        id: "message-bao-business",
        role: "BUSINESS",
        senderName: "Nova Labs",
        body: "Chào Bảo, đội ngũ đã nhận hồ sơ và đang xem phần kinh nghiệm Flutter của bạn.",
        sentAt: "16:05",
        deliveryStatus: "SEEN",
      },
      {
        id: "message-bao-talent",
        role: "TALENT",
        senderName: "Trần Quốc Bảo",
        body: "Cảm ơn đội ngũ. Mình có thể gửi thêm bản demo luồng thanh toán nếu cần.",
        sentAt: "16:12",
        deliveryStatus: "SEEN",
        replyToId: "message-bao-business",
      },
    ],
  },
  {
    id: "application-minh-anh",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    applicantUserId: "user-minh-anh",
    candidateName: "Nguyễn Minh Anh",
    initials: "MA",
    headline: "Flutter & Product Developer",
    email: "minh.anh@example.com",
    location: "TP. Hồ Chí Minh, Việt Nam",
    matchScore: 91,
    skills: ["Flutter", "Dart", "REST API"],
    coverNote:
      "Mình quan tâm đến cách Nova kết nối trải nghiệm nhận việc với luồng chi trả USDC trên mobile.",
    portfolioLabel: "github.com/minhanh-dev",
    portfolioPreview: [
      {
        id: "ma-1",
        title: "Design System Mobile",
        thumbnailUrl: "/images/dashboard-preview.webp",
        url: "https://github.com/minhanh-dev/design-system",
        description: "Hệ thống UI component tối ưu hoá cho trải nghiệm mobile",
      },
      {
        id: "ma-2",
        title: "E-Commerce App Flutter",
        url: "https://github.com/minhanh-dev/flutter-ecommerce",
        description: "Ứng dụng thương mại điện tử đa nền tảng Flutter",
      },
    ],
    availability: "Sẵn sàng từ 18/09/2026",
    status: "submitted",
    submittedAt: "12/09/2026 · 09:42",
    createdAt: "2026-09-12T09:42:00Z",
    updatedAt: "2026-09-12T09:42:00Z",
    messages: [
      {
        id: "message-anh-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được gửi đến Nova Labs.",
        sentAt: "09:42",
      },
      {
        id: "message-anh-talent",
        role: "TALENT",
        senderName: "Nguyễn Minh Anh",
        body: "Chào đội ngũ, mình sẵn sàng trao đổi thêm về kinh nghiệm Flutter và tích hợp API.",
        sentAt: "09:44",
        deliveryStatus: "DELIVERED",
      },
    ],
  },
  {
    id: "application-linh-nguyen",
    jobId: "job-product-designer",
    jobTitle: "Product Designer - Remote Workflows",
    applicantUserId: "user-linh-nguyen",
    candidateName: "Nguyễn Khánh Linh",
    initials: "KL",
    headline: "Product Designer",
    email: "linh.nguyen@example.com",
    location: "Hà Nội, Việt Nam",
    matchScore: 88,
    skills: ["Figma", "UX Research", "Design System"],
    coverNote:
      "Mình có kinh nghiệm thiết kế sản phẩm fintech và quy trình cộng tác cho đội ngũ phân tán.",
    portfolioLabel: "khanhlinh.design",
    portfolioPreview: [
      {
        id: "kl-1",
        title: "Fintech Dashboard Redesign",
        url: "https://khanhlinh.design/fintech-dashboard",
        description: "Giao diện quản lý dòng tiền và thanh toán xuyên biên giới",
      },
      {
        id: "kl-2",
        title: "Web3 Wallet Onboarding",
        url: "https://khanhlinh.design/web3-wallet",
        description: "Quy trình tạo ví và bảo mật tài sản số không mật khẩu",
      },
    ],
    availability: "Có thể bắt đầu ngay",
    status: "shortlisted",
    submittedAt: "10/09/2026 · 11:08",
    createdAt: "2026-09-10T11:08:00Z",
    updatedAt: "2026-09-10T14:30:00Z",
    messages: [
      {
        id: "message-linh-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được duyệt vào Shortlist. Hai bên có thể tiếp tục trao đổi.",
        sentAt: "14:30",
      },
    ],
  },
  {
    id: "application-phuong-thao",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    applicantUserId: "user-phuong-thao",
    candidateName: "Vũ Phương Thảo",
    initials: "PT",
    headline: "Senior Mobile Engineer",
    email: "thao.vu@example.com",
    location: "Hà Nội, Việt Nam",
    matchScore: 96,
    skills: ["Flutter", "Dart", "Rust", "Web3"],
    coverNote:
      "Mình có 4 năm kinh nghiệm xây dựng ứng dụng fintech và tích hợp ví crypto trên mobile.",
    portfolioLabel: "github.com/phuongthao-dev",
    portfolioPreview: [
      {
        id: "pt-1",
        title: "Crypto Checkout SDK",
        thumbnailUrl: "/images/payment-network.webp",
        url: "https://github.com/phuongthao-dev/crypto-checkout",
        description: "Bộ thư viện Flutter nhúng trực tiếp cổng thanh toán crypto",
      },
    ],
    availability: "Sẵn sàng ngay",
    status: "interview",
    submittedAt: "13/09/2026 · 10:15",
    createdAt: "2026-09-13T10:15:00Z",
    updatedAt: "2026-09-14T14:00:00Z",
    messages: [
      {
        id: "message-thao-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được chọn vào vòng phỏng vấn.",
        sentAt: "10:15",
      },
    ],
  },
  {
    id: "application-quoc-tuan",
    jobId: "job-product-designer",
    jobTitle: "Product Designer - Remote Workflows",
    applicantUserId: "user-quoc-tuan",
    candidateName: "Đặng Quốc Tuấn",
    initials: "QT",
    headline: "Lead UX/UI Designer",
    email: "tuan.dang@example.com",
    location: "Đà Nẵng, Việt Nam",
    matchScore: 92,
    skills: ["Figma", "Design System", "Prototyping"],
    coverNote:
      "Rất hào hứng với cơ hội hợp tác và đã hoàn tất các thỏa thuận công việc cùng Nova Labs.",
    portfolioLabel: "dribbble.com/quoctuan",
    portfolioPreview: [
      {
        id: "qt-1",
        title: "Nova Design Tokens",
        url: "https://dribbble.com/quoctuan/nova-tokens",
        description: "Thư viện design token đa nền tảng trên Figma",
      },
    ],
    availability: "Đang làm việc",
    status: "accepted",
    submittedAt: "08/09/2026 · 08:30",
    createdAt: "2026-09-08T08:30:00Z",
    updatedAt: "2026-09-15T09:00:00Z",
    messages: [
      {
        id: "message-tuan-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Hồ sơ đã được nhận chính thức (Hired).",
        sentAt: "09:00",
      },
    ],
  },
  {
    id: "application-van-hung",
    jobId: "job-rust-solana",
    jobTitle: "Solana Smart Contract Engineer",
    applicantUserId: "user-van-hung",
    candidateName: "Bùi Văn Hùng",
    initials: "VH",
    headline: "Solana / Rust Developer",
    email: "hung.bui@example.com",
    location: "Hà Nội, Việt Nam",
    matchScore: 85,
    skills: ["Rust", "Solana", "Anchor"],
    coverNote:
      "Do đã nhận một dự án dài hạn khác, mình xin phép rút hồ sơ ứng tuyển đợt này. Cảm ơn Nova Labs.",
    portfolioLabel: "github.com/hungbui-sol",
    portfolioPreview: [
      {
        id: "vh-1",
        title: "Solana Escrow Program",
        url: "https://github.com/hungbui-sol/escrow-program",
        description: "Hợp đồng thông minh lưu ký tài sản an toàn trên Solana",
      },
    ],
    availability: "Đã nhận dự án khác",
    status: "withdrawn",
    submittedAt: "09/09/2026 · 14:00",
    createdAt: "2026-09-09T14:00:00Z",
    updatedAt: "2026-09-14T11:20:00Z",
    messages: [
      {
        id: "message-hung-system",
        role: "SYSTEM",
        senderName: "Nova",
        body: "Ứng viên đã chủ động rút hồ sơ.",
        sentAt: "11:20",
      },
    ],
  },
];
