import type { CandidateApplication } from "@/types/application";

export const demoApplications: CandidateApplication[] = [
  {
    id: "application-tran-bao",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    candidateName: "Trần Quốc Bảo",
    initials: "TB",
    headline: "Frontend Developer",
    email: "bao.tran@example.com",
    location: "Đà Nẵng, Việt Nam",
    matchScore: 94,
    skills: ["Flutter", "Dart", "Firebase"],
    coverNote:
      "Mình đã xây dựng hai ứng dụng Flutter có luồng thanh toán và muốn trao đổi thêm về phạm vi tích hợp của dự án.",
    portfolioLabel: "github.com/tranbao",
    availability: "Có thể bắt đầu trong 1 tuần",
    status: "IN_REVIEW",
    submittedAt: "11/09/2026 · 15:20",
    messages: [
      {
        id: "message-bao-system",
        role: "SYSTEM",
        senderName: "NIVEX",
        body: "Hồ sơ đã được gửi đến NIVEX Labs.",
        sentAt: "15:20",
      },
      {
        id: "message-bao-business",
        role: "BUSINESS",
        senderName: "NIVEX Labs",
        body: "Chào Bảo, đội ngũ đã nhận hồ sơ và đang xem phần kinh nghiệm Flutter của bạn.",
        sentAt: "16:05",
        deliveryStatus: "SEEN",
      },
      {
        id: "message-bao-talent",
        role: "TALENT",
        senderName: "Trần Quốc Bảo",
        body: "Cảm ơn đội ngũ. Mình có thể gửi thêm bản demo luồng thanh toán nếu cần.",
        sentAt: "16:12",
        deliveryStatus: "SEEN",
        replyToId: "message-bao-business",
      },
    ],
  },
  {
    id: "application-minh-anh",
    jobId: "job-flutter-payments",
    jobTitle: "Flutter Developer - Payment Experience",
    candidateName: "Nguyễn Minh Anh",
    initials: "MA",
    headline: "Flutter & Product Developer",
    email: "minh.anh@example.com",
    location: "TP. Hồ Chí Minh, Việt Nam",
    matchScore: 91,
    skills: ["Flutter", "Dart", "REST API"],
    coverNote:
      "Mình quan tâm đến cách NIVEX kết nối trải nghiệm nhận việc với luồng chi trả USDC trên mobile.",
    portfolioLabel: "github.com/minhanh-dev",
    availability: "Sẵn sàng từ 18/09/2026",
    status: "SUBMITTED",
    submittedAt: "12/09/2026 · 09:42",
    messages: [
      {
        id: "message-anh-system",
        role: "SYSTEM",
        senderName: "NIVEX",
        body: "Hồ sơ đã được gửi đến NIVEX Labs.",
        sentAt: "09:42",
      },
      {
        id: "message-anh-talent",
        role: "TALENT",
        senderName: "Nguyễn Minh Anh",
        body: "Chào đội ngũ, mình sẵn sàng trao đổi thêm về kinh nghiệm Flutter và tích hợp API.",
        sentAt: "09:44",
        deliveryStatus: "DELIVERED",
      },
    ],
  },
  {
    id: "application-linh-nguyen",
    jobId: "job-product-designer",
    jobTitle: "Product Designer - Remote Workflows",
    candidateName: "Nguyễn Khánh Linh",
    initials: "KL",
    headline: "Product Designer",
    email: "linh.nguyen@example.com",
    location: "Hà Nội, Việt Nam",
    matchScore: 88,
    skills: ["Figma", "UX Research", "Design System"],
    coverNote:
      "Mình có kinh nghiệm thiết kế sản phẩm fintech và quy trình cộng tác cho đội ngũ phân tán.",
    portfolioLabel: "khanhlinh.design",
    availability: "Có thể bắt đầu ngay",
    status: "APPROVED",
    submittedAt: "10/09/2026 · 11:08",
    messages: [
      {
        id: "message-linh-system",
        role: "SYSTEM",
        senderName: "NIVEX",
        body: "Hồ sơ đã được duyệt. Hai bên có thể tiếp tục trao đổi.",
        sentAt: "14:30",
      },
    ],
  },
];
