import type { JobPost } from "@/types/job";

export const demoJobs: JobPost[] = [
  {
    id: "job-flutter-payments",
    organizationId: "org-nivex-demo",
    title: "Flutter Developer - Payment Experience",
    category: "Mobile Development",
    summary:
      "Xây dựng luồng nhận việc, thông báo và theo dõi thanh toán cho ứng dụng Flutter.",
    skills: ["Flutter", "Dart", "Firebase"],
    workMode: "REMOTE",
    locationScope: "Việt Nam",
    engagement: "PROJECT",
    paymentType: "MILESTONE",
    budgetMinMinor: "1200000000",
    budgetMaxMinor: "1800000000",
    duration: "6-8 tuần",
    applicationDeadline: "2026-09-24",
    status: "PUBLISHED",
    notifyMatchingTalent: true,
    matchedTalentCount: 28,
    applicantCount: 12,
    createdAt: "2026-09-08T08:30:00.000Z",
    publishedAt: "2026-09-08T09:00:00.000Z",
  },
  {
    id: "job-product-designer",
    organizationId: "org-nivex-demo",
    title: "Product Designer - Remote Workflows",
    category: "Product Design",
    summary:
      "Thiết kế trải nghiệm ứng tuyển và hồ sơ công việc cho đội ngũ làm việc từ xa.",
    skills: ["Figma", "Design System", "UX Research"],
    workMode: "REMOTE",
    locationScope: "Đông Nam Á",
    engagement: "CONTRACT",
    paymentType: "FIXED",
    budgetMinMinor: "800000000",
    budgetMaxMinor: "1200000000",
    duration: "4 tuần",
    applicationDeadline: "2026-09-20",
    status: "PUBLISHED",
    notifyMatchingTalent: true,
    matchedTalentCount: 19,
    applicantCount: 7,
    createdAt: "2026-09-06T03:10:00.000Z",
    publishedAt: "2026-09-06T04:00:00.000Z",
  },
  {
    id: "job-solana-integration",
    organizationId: "org-nivex-demo",
    title: "Solana Integration Engineer",
    category: "Blockchain Engineering",
    summary:
      "Tích hợp theo dõi giao dịch Devnet và trạng thái xác nhận vào hệ thống thanh toán.",
    skills: ["Solana", "TypeScript", "RPC"],
    workMode: "REMOTE",
    locationScope: "Toàn cầu",
    engagement: "PROJECT",
    paymentType: "MILESTONE",
    budgetMinMinor: "2000000000",
    budgetMaxMinor: "3200000000",
    duration: "8-10 tuần",
    applicationDeadline: "2026-10-01",
    status: "DRAFT",
    notifyMatchingTalent: false,
    matchedTalentCount: 0,
    applicantCount: 0,
    createdAt: "2026-09-09T02:15:00.000Z",
  },
  {
    id: "job-content-operations",
    organizationId: "org-nivex-demo",
    title: "Content Operations Specialist",
    category: "Operations",
    summary:
      "Chuẩn hóa nội dung công việc và vận hành chương trình cộng tác viên theo dự án.",
    skills: ["Operations", "Content", "English"],
    workMode: "REMOTE",
    locationScope: "Việt Nam",
    engagement: "PART_TIME",
    paymentType: "HOURLY",
    budgetMinMinor: "12000000",
    budgetMaxMinor: "18000000",
    duration: "3 tháng",
    applicationDeadline: "2026-09-12",
    status: "CLOSED",
    notifyMatchingTalent: true,
    matchedTalentCount: 34,
    applicantCount: 21,
    createdAt: "2026-08-20T10:00:00.000Z",
    publishedAt: "2026-08-21T02:00:00.000Z",
  },
];
